name: Bug Report
description: Report a bug in csv2notion
title: "[Bug]: "
labels: "bug"
body:
- type: input
  attributes:
    label: csv2notion-neo version
    description: What version of csv2notion are you using? If unsure, run `csv2notion-neo --version`
  validations:
    required: true
- type: dropdown
  attributes:
    label: What OS are you using?
    options:
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
- type: input
  attributes:
    label: OS Version / Linux distribution
    description: What OS version or Linux distribution version are you using?
    placeholder: "e.g. Windows 10, Ubuntu 20.04"
  validations:
    required: true
- type: textarea
  attributes:
    label: Bug description
    description: A clear description of the bug and how to reproduce it.
  validations:
    required: true
- type: textarea
  attributes:
    label: Log excerpt
    description: If possible, please attach log excerpt
    render: shell
