name: notion_image_upload_test

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release after build'
        required: true
        default: 'no'
      
jobs:
  build:
    runs-on: macos-15  # Ensure we run on macOS

    steps:
    - name: Verify Runner Architecture (ARM64 Check)
      run: |
        ARCH=$(uname -m)
        echo "Running on architecture: $ARCH"
        if [[ "$ARCH" != "arm64" ]]; then
          echo "❌ ERROR: This workflow requires an ARM-based Mac (M1/M2)."
          exit 1
        fi

    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Create Test Directory
      run: mkdir -p notion-test/data-set
    
    - name: Prepare Directories
      run: |
        PARENT=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
        mkdir -p "$PARENT/notion-test/data-set/json"

    - name: Copy Test Directory
      run: |
        mkdir -p notion-test/data-set
        mkdir -p notion-test/data-set/json
        cp -R ./test/json/. ./notion-test/data-set/json

    - name: Verify Copied Files
      run: |
        echo "Checking copied files..."
        ls -l ./notion-test/
        ls -l ./notion-test/data-set
        ls -l ./notion-test/data-set/json

    - name: Get Latest CSV2Notion Neo Release URL
      run: |
        LATEST_URL=$(curl -s https://api.github.com/repos/TheAcharya/csv2notion-neo/releases/latest | \
        jq -r '.assets[] | select(.name | endswith(".pkg")) | .browser_download_url')
        
        echo "Latest release URL: $LATEST_URL"
        echo "DOWNLOAD_URL=$LATEST_URL" >> $GITHUB_ENV

    - name: Download CSV2Notion Neo macOS Package
      run: |
        curl -L -o ./notion-test/CSV2Notion-Neo.pkg "$DOWNLOAD_URL"

    - name: Install CSV2Notio -Neo Package
      run: |
        sudo installer -pkg ./notion-test/CSV2Notion-Neo.pkg -target /

    - name: Verify CSV2Notion Neo Installation
      run: |
        if ! command -v csv2notion_neo &> /dev/null
        then
          echo "❌ ERROR: csv2notion_neo is not installed or not in PATH."
          exit 1
        fi

        echo "✅ CSV2Notion-Neo installed successfully!"
        echo "Checking version..."
        csv2notion_neo --version
