name: notion_image_upload_test

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * 6' # Runs at 8 AM Singapore time (00:00 UTC) every Saturday
      
env:
  BUILD_PYTHON_VERSION: 3.8
  BUILD_POETRY_VERSION: 1.4
  PACKAGE_NAME: csv2notion_neo

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Set up Poetry ${{ env.BUILD_POETRY_VERSION }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.BUILD_POETRY_VERSION }}

      - name: Install the neccessary libraries to run csv2notion_neo
        run: poetry config virtualenvs.create false && \
             poetry install --no-root && \
             rm -rf /root/.cache/pypoetry

      - name: Run tests
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish