name: notion_image_upload_test

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * 6' # Runs at 8 AM Singapore time (00:00 UTC) every Saturday
      
env:
  BUILD_PYTHON_VERSION: 3.8
  BUILD_POETRY_VERSION: 1.4
  PACKAGE_NAME: csv2notion_neo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Set up Poetry ${{ env.BUILD_POETRY_VERSION }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.BUILD_POETRY_VERSION }}
      
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with: 
          path: |
            .venv
            ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-
              
      - name: Install the neccessary libraries to run csv2notion_neo
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Run tests
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          NOTION_TOKEN_A: ${{secrets.NOTION_TOKEN_A}}
          NOTION_URL_A: ${{secrets.NOTION_URL_A}}

        run: pytest -v -s 