name: release_brew

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: csv2notion

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.BREW_BUMP_TOKEN }}
          tap: vzhd1701/tap
          formula: ${{ env.PACKAGE_NAME }}
          tag: ${{ steps.get-latest-tag.outputs.tag }}
