name: release_brew

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: csv2notion

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.BREW_BUMP_TOKEN }}
          tap: vzhd1701/tap
          formula: ${{ env.PACKAGE_NAME }}
